
spring:
  application:
    name: discovery-service
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  org:
    netflix:
      eureka: OFF
  pattern:
    console: '%msg%n'

